name: Test
on: 
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TEST4:  Test4
    steps:
    - name: Build the Docker container image
      env: 
        TEST: "foo"
        TEST2: "${{env.TEST4}}/test"
      run: |
        echo "hello world" 
        for((i=1;i<=1000;i+=1)); do echo "Welcome $i times"; sleep 0.1; done
  build2:
    name: Build2
    runs-on: ubuntu-latest
    env:
      TEST4:  Test4
    steps:
    - name: Build the Docker container image
      env: 
        TEST: "foo"
        TEST2: "${{env.TEST4}}/test"
      run: |
        echo "hello world" 
        echo $TEST2
        
