name: "cd"
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  cd:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
