name: testmatrix
on:
 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10,12,14,15]
    concurrency: ${{ matrix.node }}
        
    steps:
      - run: echo "Hi there"
      - run: echo "${{ matrix.node }}"
