name: test fedora curl

on:
  push:

jobs:
  curl-test:
    environment: t🥑st2
    runs-on: ubuntu-latest
    steps:
      - name: fedora curl testing
        run: |
          curl -v "https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-32&arch=x86_64" 
