name: testmatrix
on:
 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node: [101,121,141,151]
    concurrency: ${{ matrix.node }}
        
    steps:
      - run: sleep 500
      - run: echo "Hi there"
      - run: echo "${{ matrix.node }}"
